---

- name: publish microservice gate image
  docker_image:
    name: "{{init_mongo_image_name}}"
    tag: "{{init_mongo_image_git_version}}"
    push: yes
    repository: "{{login}}/{{repository}}"
...
